language: go
branches:
  only:
  - source
install:
- go get -v github.com/spf13/hugo
script:
- hugo -v
deploy:
  local_dir: public
  provider: pages
  target_branch: master
  fqdn: 'artistjanet.com'
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: source
