language: go
branches:
  only:
  - source
install:
- go get -v github.com/spf13/hugo
script:
- hugo -v
deploy:
  local_dir: public
  provider: pages
  target_branch: master
  fqdn: 'artistjanet.com'
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: source
after_deploy:
  - |
    curl -X DELETE "https://api.cloudflare.com/client/v4/zones/${CF_ZONE_ID}/purge_cache" \
     -H "X-Auth-Email: ${CF_EMAIL}" \
     -H "X-Auth-Key: ${CF_API_KEY}" \
     -H "Content-Type: application/json" \
     --data '{"purge_everything":true}'
