baseurl = "http://mum.jmsbrdy.com/"
languageCode = "en-us"
title = "Janet Brady"
theme = "hugo-strata-theme"
disqusShortname = ""
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
  # To provide some metadata for search engines feel free to add a few
  # information about you and your website.
  name = "Janet Brady"
  description = "I'm an artist"

  # Format dates with Go's time formatting
  date_format = "2006-01-02"

  # Add custom assets with their paths relative to the static folder
  custom_js   = []
  custom_css  = []

  [params.sidebar]
    # Replace the avatar with a picture of your own under static/images
    avatar = "avatar.jpg"
    # Use Markdown to format the string. This works nearly all over the theme
    bio = "To wander and wonder at people and places is fantastic. Here are some of the images I've seen on my journey so far…"

    # The icons will be shown if you enter your username
    twitter = ""
    github = ""
    dribbble = ""
    facebook = ""
    googleplus = ""
    flickr = ""
    linkedin = ""

    copyright = [
      "&copy; Janet Brady"
    ]


  [params.about]
    hide  = false
    title = "About me"
    content = "I'm wondering as I walk… could this mean disaster! I see settlements and trackways making patterns which evolve and dissolve in time. I see patterns in natural landscapes which evolve and dissolve too. Over millennia life comes and goes leaving a particular stamp on Place. The place leaves its own mark on the people too."


  [params.portfolio]
    hide  = false
    title = "Recent Work"

    # The images and thumbnails are stored under static/images
    # Create and change subfolders as you like
    [[params.portfolio.gallery]]
      image = "fulls/Allotment-Invaders.jpg"
      thumb = "thumbs/Allotment-Invaders.jpg"
      title = "Allotment Invaders"
      description = "Collagraph. 40×50cm."

    [[params.portfolio.gallery]]
      image = "fulls/Shifting-Sands-of-the-Kent-Estuary.jpg"
      thumb = "thumbs/Shifting-Sands-of-the-Kent-Estuary.jpg"
      title = "Shifting Sands of the Kent Estuary"
      description = "Superimposed solar etchings. 20×15cm."

    [[params.portfolio.gallery]]
      image = "fulls/Washing-Lines-Ravenglass.jpg"
      thumb = "thumbs/Washing-Lines-Ravenglass.jpg"
      title = "Washing Lines, Ravenglass"
      description = ""

  [params.recentposts]
    hide  = true
    title = "Posts"

  [params.contact]
    hide  = false
    title = "Get In Touch"
    content = "Accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna. Accumsan orci faucibus id eu lorem semper nunc nisi lorem vulputate lorem neque lorem ipsum dolor."

    address = [
      "1234 Somewhere Rd.",
      "Nashville, TN 00000",
      "United States"
    ]
    phone = "000-000-0000"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
      #
      # What you need to do for the setup?
      #
      # - set your email address under 'email' below
      # - upload the generated site to your server
      # - send a dummy email yourself to confirm your account
      # - click the confirm link in the email from www.formspree.io
      # - you're done. Happy mailing!
    email = "hello@example.com"

    [params.contact.form]
      # Set custom strings for the form if your native
      # language isn't English
      name = "Name"
      email = "Email"
      message = "Message"
      submit = "Send message"


# Menu links that appear on the left sidebar
[[menu.main]]
  name = "Home"
  url  = "/"
  weight = 0

# [[menu.main]]
#   name = "Projects"
#   url  = "post/"
#   weight = 10
